layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
   hackerrank: gauthamkrishnan1
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: C++
    web_url: https://en.wikipedia.org/wiki/C%2B%2B
    image_url: https://en.wikipedia.org/wiki/C%2B%2B#/media/File:ISO_C++_Logo.svg

  - name: Python
    web_url: https://www.python.org/
    image_url: https://en.wikipedia.org/wiki/Python_(programming_language)#/media/File:Python-logo-notext.svg

  - name: Arduino
    web_url: https://www.arduino.cc/
    image_url: https://icon2.cleanpng.com/20180715/skh/kisspng-arduino-computer-software-library-electronics-arduino-logo-5b4beae2df7ab1.6638086415317019869154.jpg
